- include/services/DiscordService.h
- src/CMakeLists.txt
- src/managers/LanguageManager.cpp
- src/services/DiscordService.cpp
- src/services/DotaService.cpp
Language detection provided by Discord.
See issue #5 to more details.
> [Feature] Discord language detection

- controllers/Listener.cc
- include/services/DotaService.h
- lang/en-us.json
- lang/pt-br.json
- lang/ru-ru.json
- lang/uk-ua.json
- src/CMakeLists.txt
- src/services/DiscordService.cpp
- src/services/DotaService.cpp
Support detection of matches with bots.
> [Feature] Bot Match detection

- README.md
- include/managers/ConfigurationManager.h
- include/services/DotaService.h
- lang/en-us.json
- lang/pt-br.json
- lang/ru-ru.json
- lang/uk-ua.json
- src/managers/ConfigurationManager.cpp
- src/services/DotaService.cpp
- src/templates/config/config.json
- src/templates/templates/gamestate_integration_rpc.cfg
Aegis of the Immortal detection support. Displaying along with the effects/buffs.
> [Feature] Aegis detection

- README.md
- include/managers/ConfigurationManager.h
- include/services/DotaService.h
- src/managers/ConfigurationManager.cpp
- src/services/DotaService.cpp
- src/templates/config/config.json
Language change support via config.json
> [Feature] Language Selection

- CMakeLists.txt
- README.md
- controllers/Listener.cc
- include/managers/ConfigurationManager.h
- include/managers/SteamManager.h
- include/managers/WebServerManager.h
- include/persistence/FileLoader.h
- include/persistence/JsonLoader.h
- lang/en-us.json
- lang/pt-br.json
- lang/ru-ru.json
- lang/uk-ua.json
- main.cc
- src/CMakeLists.txt
- src/managers/ConfigurationManager.cpp
- src/managers/LanguageManager.cpp
- src/managers/SteamManager.cpp
- src/managers/WebServerManager.cpp
- src/persistence/FileLoader.cpp
- src/persistence/JsonLoader.cpp
A more user-friendly installation flow. With more options to identify errors.
* Search for Steam in the common folder. Otherwise, ask for information.
* Search for Dota in your library. Otherwise, ask to inform.
* Show instructions to install manually in case of failure
> [Feature] CFG -  Installation

- CMakeLists.txt
- README.md
- include/managers/WebServerManager.h
- include/services/DiscordService.h
- main.cc
- src/managers/ConfigurationManager.cpp
- src/services/DiscordService.cpp
An experimental version of the application made for Linux
> [Feature] Experimental Linux Support

- include/extensions/StringExtensions.h
- lang/en-us.json
- lang/es-es.json
- lang/pt-br.json
- lang/ru-ru.json
- lang/uk-ua.json
- main.cc
- src/extensions/StringExtensions.cpp
- src/managers/SteamManager.cpp
Fixing issue that considers any game numbered 570 as Dota.
The installation process has also become more verbose.
> [Fix] Considering any game with the number 570 as Dota

- .github/workflows/issues.yml
Allows automatic closing of abandoned issues
> [Feature] Automatic Close Issues

- .github/workflows/build.yml
- CMakePresets.json
- vcpkg.json
Automatic generation of builds when a pull request is performed
> [Feature] Automatic Build using MSVC

- web/angular.json
- web/package-lock.json
- web/package.json
- web/src/app/ui/index/index.component.html
- web/src/app/ui/index/index.component.scss
- web/tsconfig.json
Add the "see discussions" button at the bottom of the page and update the packages
> [Feature] Discussions option in homepage

- lang/en-us.json
- lang/es-es.json
- lang/ja-jp.json
- lang/pt-br.json
- lang/ru-ru.json
- lang/uk-ua.json
- src/services/DotaService.cpp
Add Faceless Void Arcana Detection.
> Arcana images will be updated on discord later.
> [Feature] Faceless Void Arcana

- lang/en-us.json
- lang/es-es.json
- lang/ja-jp.json
- lang/pt-br.json
- lang/ru-ru.json
- lang/uk-ua.json
Added lines for the Dark moon map
> [Feature] Dark Moon Map Support

- lang/en-us.json
- lang/es-es.json
- lang/ja-jp.json
- lang/pt-br.json
- lang/ru-ru.json
- lang/uk-ua.json
- src/services/DotaService.cpp
Add Phantom Assassin Person Detection
> [Feature]: Phantom Assassin Person Detection

- src/services/DotaService.cpp
Fixed missing Zeus arcana reference.
> [Fix] Zeus Arcana Reference

- lang/en-us.json
- lang/es-es.json
- lang/ja-jp.json
- lang/pt-br.json
- lang/ru-ru.json
- lang/th-th.json
- lang/uk-ua.json
- src/services/DotaService.cpp
Add Crystal Maiden Persona Detection
> [Feature]: Crystal Maiden Persona Detection 

- lang/en-us.json
- lang/es-es.json
- lang/ja-jp.json
- lang/pt-br.json
- lang/ru-ru.json
- lang/th-th.json
- lang/uk-ua.json
> [Feature]: Diretide Support

- lang/ru-ru.json
Changed the string to use localized event name
> Minor fix to Russian translation

- CMakeLists.txt
- src/services/DiscordService.cpp
Update Discord SDK 2.5.6 to 3.2.1
> [Improvement]: Discord SDK

- lang/en-us.json
- lang/es-es.json
- lang/ja-jp.json
- lang/pt-br.json
- lang/ru-ru.json
- lang/th-th.json
- lang/uk-ua.json
- src/services/DotaService.cpp
Add Razor Arcana Detection
Closes #49
> [Feature]: Razor Arcana Detection

- lang/en-us.json
- lang/es-es.json
- lang/ja-jp.json
- lang/pt-br.json
- lang/ru-ru.json
- lang/th-th.json
- lang/uk-ua.json
- src/services/DotaService.cpp
Added Muerta Strings
> Also fixes a stdout of wearables
Closes #52
> [Feature]: Muerta Strings

- lang/es-es.json
Translated some untranslated strings and fixed minor errors.
> Minor Translation Fixes
